### ISSUE TITLE
[feature request] autodetect type from default

### ISSUE THREAD

**Issue by jtprince** [matheusmoreira/acclaim#2]
Some other commandline utilities allow a user to specify a default without specifying a type.  The type of the default is then used to specify the type (internally).

**Comment by matheusmoreira** [comment]
Done! Found and fixed a bug to boot!

**Comment by jtprince** [comment]
Thank you, Matheus, for considering and implementing these features.  As I mentioned, I've used and poked around lots of commandline code bases, and even implemented my own commandline parser based on optparse.  Although it made some things easier, in the end it was not very extensible so it just turned into a mess and I gave up on using optparse under the hood.  I revisited the existing parsers, looking for a better foundation, and I revisited acclaim.  I love the way you've organized the code, making a string distinction between the foundational classes and the DSL.  Your dsl is awesome--extremely terse with no fluff at all.

I don't think it's unreasonable to consider Acclaim the best parser out there.  Maybe you should lead off your README with a bullet list of features:
- highly concise syntax, one line per option
  - defaults inferred from class type
- can perform arbitrarily complex casting
- elegant subcommand system
- easy to extend/modify
  - written from the ground-up (no dependence on optparse)
  - clean distinction between the foundational classes and the DSL
- can add arbitrary descriptions, examples, or notes to the help message
- fits the help message to the terminal width
- ability to set option defaults piecemeal or all at once [coming]
- can group options [coming]

**Comment by matheusmoreira** [comment]
No problem! It's great that you have experience with other libraries. Although I try to leave as much room for expansion as possible, I was focusing mostly on my own needs at first. It helps a lot to be presented with different use cases.

The `README` really needs an update. Before I ship version 0.6.0, I'll put all the examples into the `examples/` directory, then I'll read the source code again and write a new one.

I keep a TODO list in [evernote](https://evernote.com/), I'll put that in the repository as well.

**Comment by jtprince** [comment]
> I was focusing mostly on my own needs at first. It helps a lot to be
> presented with different use cases.

I agree with this philosophy since if you don't need it, then it's really
not worth implementing, and it can always be extended later if the design
is sane.  Thanks again for considering these other use cases.  I see a lot
of potential with acclaim, so I thought I would toss those into the pot
while you seem to be actively developing.  Will be interesting to see what
all you have planned in the TODO.
